### ISSUE TITLE
Set Clock with correct timezone

### ISSUE THREAD

**Issue by TeraJaQ** [michaelmiklis/docker-rpi-monitor#12]
how set the correct timezone?

**Comment by TeraJaQ** [comment]
sorry for the disturb but i've solved by adding a TZ= Europe/Rome in the environment section inside the docker-compose..
This is my docker-compose.yml
```
version: '3'
services:
  rpi-monitor:
    container_name: rpi-monitor
    image: michaelmiklis/rpi-monitor:latest
    restart: unless-stopped
    devices:
      - /dev/vcsm-cma:/dev/vcsm-cma
      - /dev/vchiq:/dev/vchiq
    volumes:
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - /etc:/dockerhost/etc:ro
      - /sys:/dockerhost/sys:ro
      - /boot:/boot
      - /opt/vc:/opt/vc
      - ./cgroup:/sys/fs/cgroup
#      - ./rpimonitor:/etc/rpimonitor  
#      - ./stat:/var/lib/rpimonitor/stat  #to store rrd db but don't work
    environment:
    - TZ=Europe/Rome
    ports:
    - "8888:8888"
```
