### ISSUE TITLE
Run Docker - Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/vcsm": no such file or directory. 

### ISSUE THREAD

**Issue by sebastienhouzet** [michaelmiklis/docker-rpi-monitor#4]
Hello

I have an error during run docker : 

root@pihome:/home/pi# docker run --device=/dev/vchiq --device=/dev/vcsm --volume=/opt/vc:/opt/vc --volume=/boot:/boot --volume=/sys:/dockerhost/sys:ro --volume=/etc:/dockerhost/etc:ro --volume=/proc:/dockerhost/proc:ro --volume=/usr/lib:/dockerhost/usr/lib:ro -p=8888:8888 --name="rpi-monitor" -d  michaelmiklis/rpi-monitor:latest
73163e6ff8c1d98ba0d80f5b34ad0f637df7f3ce6c75e241b0dfcfcf393269a6

**docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/vcsm": no such file or directory.**

**Comment by beercity** [comment]
Having the same issue. I removed --device=/dev/vcsm from the command which works, but I am not sure what metrics I am missing now.

**Comment by jamesbiederbeck** [comment]
What platform are you folks on? I got this on a pi4 running a gutted debian-based distro

**Comment by mcgyver83** [comment]
Same issue for me with a rpi 2B with Buster.

**Comment by Ubique88** [comment]
Is there any update on this?

**Comment by jamesbiederbeck** [comment]
@Ubique88  did you try this:

> Having the same issue. I removed --device=/dev/vcsm from the command which works, but I am not sure what metrics I am missing now.

**Comment by NuAlex** [comment]
I posted this same issue under [Issue #10](https://github.com/michaelmiklis/docker-rpi-monitor/issues/10), my bad. 

To fix it, you just need to replace **--device=/dev/vcsm** by **--device=/dev/vcsm-cma**

Here's the fixed command:

```
docker run --device=/dev/vchiq \
--device=/dev/vcsm-cma \
--volume=/opt/vc:/opt/vc \
--volume=/boot:/boot \
--volume=/sys:/dockerhost/sys:ro \
--volume=/etc:/dockerhost/etc:ro \
--volume=/proc:/dockerhost/proc:ro \
--volume=/usr/lib:/dockerhost/usr/lib:ro \
-p=8888:8888 \
--name="rpi-monitor" \
-d \
michaelmiklis/rpi-monitor:latest

```

And the expected output :

```
Unable to find image 'michaelmiklis/rpi-monitor:latest' locally
latest: Pulling from michaelmiklis/rpi-monitor
767a78b74803: Pull complete
(...)
Digest: sha256:######9f2b643ba0######3b8cc316######020aa52fb73c######
Status: Downloaded newer image for michaelmiklis/rpi-monitor:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
######b768e3eda8c09e######97a4a97563######4fa2d57c88386e######
```

Hope this helps.

Credit goes to @serotonie
Thank you!

**Comment by mpuff** [comment]
i have the same problem on a pi4 with debian buster, i only have in /dev/ these folders:
vcs    vcs1   vcs2   vcs3   vcs4   vcs5   vcs6   vcsa   vcsa1  vcsa2  vcsa3  vcsa4  vcsa5  vcsa6  vcsu   vcsu1  vcsu2  vcsu3  vcsu4  vcsu5  vcsu6

no vcsm ore vcsm-cma

so i have changed the --device=/dev/vcsm by --device=/dev/vcs, the container is running and all data change in gui, so it looks like ok

**Comment by mcgyver83** [comment]
I haven't any --device in my docker run script.
I tried adding --device=/dev/vcs but still get the warning message (raspberry pi2 with buster)

**Comment by kaluxx** [comment]
I have  the same issues:
> ERROR: for rpi-monitor  Cannot start service rpi-monitor: error gathering device information while adding custom device "/dev/vcsm": no such file or directory

Pi4. Independent of the device configurations proposed above.

- /dev/vcsm (worked over years)
- /dev/vcsm-cma 
- /dev/vcs
- no-entry

Warning and docker will not start

**Comment by maxidebello** [comment]
should we just close this?

**Comment by boomramada** [comment]
> should we just close this?

No, I'm using Pi4 and I don't have 
/dev/vcsm or /dev/vcsm-cma and docker won't start. Still broken.

**Comment by Goro2030** [comment]
I think this shouldn't be closed @maxidebello until this is clarified for users, depending on the PI they use, which vsc/vcsm-cma o vcsm should they use, and clarify that in the README

**Comment by johntdavis84** [comment]
Thanks for this. Just trying to deploy this container for the first time ever, and ran into the device issue.

**Platform:**
```
||||||||| ||||    panoptitom@teletraan1
||||||||| ||||    os     Manjaro ARM Linux
||||      ||||    host   Raspberry Pi 4 Model B Rev 1.1
|||| |||| ||||    kernel 5.12.10-1-MANJARO-ARM
|||| |||| ||||    uptime 6d 6m
|||| |||| ||||    pkgs   1165
|||| |||| ||||    memory 946M / 3803M

Linux $hostname 5.12.10-1-MANJARO-ARM #1 SMP PREEMPT Mon Jun 14 09:55:08 CDT 2021 aarch64 GNU/Linux
```

I just got it working, on first attempt, with `/dev/vcsm-cma`.

I also didn't see any warning about using the wrong platform, even though the only tag I see on Docker Hub says it's for AMD64.

Some of the sensors and UI aren't reporting correctly, but it works. :)

**Comment by mcgyver83** [comment]
I didn't get exactly where is the issue, I found issues from others projects/images complaining the same topic.
As said above, I tried the suggestions given but no luck.

**Comment by gist901** [comment]
Here is the docker compose file that I used to get it to work. I replace ```vscm``` with ```vcs```. Everything appears to be working.

Takes a minute for the container to start working once you deploy.

```
version: '2'

services:

  rpi-monitor:
    container_name: rpi-monitor
    image: michaelmiklis/rpi-monitor:latest
    ports:
      - 8888:8888
    devices:
      - /dev/vchiq
      - /dev/vcs
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    restart: unless-stopped
```

**Comment by mauroao** [comment]
I changed it to "vcsm-cma" and now works fine!
Raspberry Pi 4

**Comment by MavBam** [comment]
***Raspberry Pi 5- 8Gb***

So, I thought I'd chime in on this as it's been pecking my head too.  

I had two issues besides the one missing by OP, as I was missing both **vcsim** and **vchiq** under /dev.

I renamed **vcsim** to **vcs**, and I ran the following to see what device **vchiq** was running under:

`lsmod | grep -E "vchiq|cec|bcm2835"`

This gave me the following result:

```
spi_bcm2835            49152  0
cec                    65536  1 vc4
```

So, I changed the install to the following and it's working very well!  It still errors about the platform mismatch (_**The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested)**_, but it is working in docker without any issues.
```
docker run --device=/dev/vcs4 --device=/dev/vcs --volume=/opt/vc:/opt/vc --volume=/boot:/boot -- volume=/sys:/dockerhost/sys:ro --volume=/etc:/dockerhost/etc:ro --volume=/proc:/dockerhost/proc:ro --volume=/usr/lib:/dockerhost/usr/lib:ro -p=8888:8888 --name="rpi-monitor" -d  michaelmiklis/rpi-monitor:latest
```

**Comment by Goro2030** [comment]
Thanks for the collaboration ... looks like the maintainer abandoned the project?

Here's my docker-compose file for RPI5-8GB

```
  rpi-monitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpi-monitor
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /mnt/usb:/mnt/usb  #Can't seem to get RPI-Monitor to read an external drive, in this case, mounted.
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    devices:
      - "/dev/vcs4:/dev/vcs4"
      - "/dev/vcs:/dev/vcs"
      - "/dev/mmcblk0:/dev/mmcblk0" #SD Card 
    restart: unless-stopped
    ports:
      - 8888:8888
```
